<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Generate New Image_RadCaptcha1CaptchaTextBox</name>
   <tag></tag>
   <elementGuidId>ecdb2edc-69f6-4228-ac52-1d21b423eafd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='RadCaptcha1_CaptchaTextBox']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#RadCaptcha1_CaptchaTextBox</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e8073fd0-7405-4558-a845-e909c719bf0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>RadCaptcha1$CaptchaTextBox</value>
      <webElementGuid>0572c11d-f353-42eb-96d3-308b6f28ac3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>34dad1cc-3376-4fc2-b911-ce7d2f22b543</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>2fee8fb9-038d-47f1-91b2-cc7bb087739c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>RadCaptcha1_CaptchaTextBox</value>
      <webElementGuid>3a5d3235-a5c6-47ab-8aa9-6a564ef6d1fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>fd944673-6729-4771-acfb-c2f58822a5f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>6ae90ac4-4952-4d1a-871c-6ba5402b1db1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;RadCaptcha1_CaptchaTextBox&quot;)</value>
      <webElementGuid>b6d4cc66-3ec7-46f6-a58e-14fc89cdee10</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='RadCaptcha1_CaptchaTextBox']</value>
      <webElementGuid>28e0c4a2-02e6-49d8-8393-a2797956805f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='RadCaptcha1_SpamProtectorPanel']/p/input</value>
      <webElementGuid>a207d18d-25b6-448f-bd64-267297e4ec5c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p/input</value>
      <webElementGuid>393757c7-6022-4a5c-981f-f26284a31d6b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'RadCaptcha1$CaptchaTextBox' and @type = 'text' and @id = 'RadCaptcha1_CaptchaTextBox']</value>
      <webElementGuid>6515708e-c2ef-4cd5-b39d-31d236f6d0b6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
