<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Attachments_btnAttached</name>
   <tag></tag>
   <elementGuidId>29057b9b-2fc9-4ef5-a825-5e85e11ed54f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#btnAttached</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='btnAttached']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>aeeb0770-a934-4b66-b35a-da693ce59141</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btnAttached</value>
      <webElementGuid>2fcef771-e893-4b61-b167-636ff74eac74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>buttons</value>
      <webElementGuid>e165fc4a-25d6-4c71-a395-3ab3717c5b22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>javascript:clkAttached123()</value>
      <webElementGuid>0e0acb2d-105b-4b14-bc66-ede61941d8c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Select Files</value>
      <webElementGuid>5121aa22-9b61-47de-b3f7-07c6cef6affe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>e0a10dc0-8e14-49b7-8190-ab5a4688c140</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>btnAttached</value>
      <webElementGuid>4c1391de-f3bd-4677-9217-8fa6f9977f26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>5ba06afb-7ef1-410f-b46b-5e4911090340</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btnAttached&quot;)</value>
      <webElementGuid>15d849b1-1140-429a-94aa-78e665f5b392</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='btnAttached']</value>
      <webElementGuid>56a21ec6-dd21-4f93-be50-0a2c6075522d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='trBtmAttach']/td[2]/input</value>
      <webElementGuid>c9dab727-c4da-4038-9854-025d8a759a18</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/input</value>
      <webElementGuid>d5620e24-e1b4-4a88-a3f6-150686c9f459</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'btnAttached' and @type = 'button' and @name = 'btnAttached']</value>
      <webElementGuid>ebd58392-6b97-4f08-8927-3260960f4b81</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
