<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Area Details</name>
   <tag></tag>
   <elementGuidId>7ea9858b-9eb8-4b79-81e5-159ecb6e5865</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#nav_item_3 > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='nav_item_3']/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>18693547-0fe0-4057-97f2-509e90f08991</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/BPAMSCLIENT2/Pages/Areadetails.aspx</value>
      <webElementGuid>46aa436f-e5ab-439b-9bd6-ebbf290a9d14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Area Details</value>
      <webElementGuid>81a59942-8dfd-4d12-b2c8-b6af75c5e8fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nav_item_3&quot;)/a[1]</value>
      <webElementGuid>2e169419-f8f7-417c-b693-dd514c98cc64</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='nav_item_3']/a</value>
      <webElementGuid>d50f3f56-8c91-487f-bc2c-57a80ab4d7f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Area Details')]</value>
      <webElementGuid>fc1c4169-5ce9-4b98-ab87-def862f4ac74</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Building Details'])[1]/following::a[1]</value>
      <webElementGuid>6ab7c98c-25e5-4645-a661-f595ca32c6e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Applicant Details'])[1]/following::a[2]</value>
      <webElementGuid>313f5ebb-8212-4343-9563-f046bab4885b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Project Library'])[1]/preceding::a[1]</value>
      <webElementGuid>58caa8ab-9118-4643-a6b2-d9c8f361a2ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='BG Details'])[1]/preceding::a[2]</value>
      <webElementGuid>3d639017-dfe7-4cab-856b-93cce2d46bf5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Area Details']/parent::*</value>
      <webElementGuid>0241d1b0-f172-4465-b559-80ba5f1b9168</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/BPAMSCLIENT2/Pages/Areadetails.aspx')]</value>
      <webElementGuid>9c288d23-cb89-49c1-a98f-3e4c7496310f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//nav/ul/li[4]/a</value>
      <webElementGuid>5d13a999-a648-4eaa-a7da-81cbe18afc01</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/BPAMSCLIENT2/Pages/Areadetails.aspx' and (text() = 'Area Details' or . = 'Area Details')]</value>
      <webElementGuid>bc395f79-064a-4393-9d83-24d980464602</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
