<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_BG Details</name>
   <tag></tag>
   <elementGuidId>1e1966bf-7951-4d0e-a376-89ad9d8f8927</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='nav_item_7&amp;PType=0']/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>92552ebf-5e70-49f1-b737-db11c9695388</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/AutoDCR.SWC.WebUI/BG/F1.aspx</value>
      <webElementGuid>1f10392c-2657-4e51-97d1-87d02a2f67f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>BG Details</value>
      <webElementGuid>a55bd1bc-7434-436c-836f-9b9dff4547a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nav_item_7&amp;PType=0&quot;)/a[1]</value>
      <webElementGuid>581c7f01-f295-48d4-9369-5d60d7992e37</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='nav_item_7&amp;PType=0']/a</value>
      <webElementGuid>77be4f52-b486-4cc1-83bd-a7a38cbce3a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'BG Details')]</value>
      <webElementGuid>c978db0c-3fa7-4c0d-a56c-ce03605bd78a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Project Library'])[1]/following::a[1]</value>
      <webElementGuid>54fe154b-1407-4cf4-a1ed-8749cc18374f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Area Details'])[1]/following::a[2]</value>
      <webElementGuid>2134c9c4-a7db-4a32-a0c6-e06f442f9339</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Submit Application'])[1]/preceding::a[2]</value>
      <webElementGuid>6435be91-e292-404c-918d-7da9bb68b984</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='BG Details']/parent::*</value>
      <webElementGuid>53ae8ce0-26f6-4342-911d-162e6413a798</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/AutoDCR.SWC.WebUI/BG/F1.aspx')]</value>
      <webElementGuid>3230bf6e-1879-489d-800d-6e8581d2e79a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[6]/a</value>
      <webElementGuid>34ed7e45-b196-4748-ac07-3017d88a2856</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/AutoDCR.SWC.WebUI/BG/F1.aspx' and (text() = 'BG Details' or . = 'BG Details')]</value>
      <webElementGuid>b9bfcf82-18cc-4029-8685-ffeebed0ac20</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
