<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Building Details</name>
   <tag></tag>
   <elementGuidId>aafa070f-95e1-4995-bf9e-4bea21140090</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#nav_item_5 > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='nav_item_5']/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>e93275d9-3888-40da-9610-dfaafb4ae44f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/BPAMSCLIENT2/Pages/WingDetails.aspx</value>
      <webElementGuid>164514b3-3631-4b7e-ad06-84a28b682fa1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Building Details</value>
      <webElementGuid>885bf294-096a-424a-9188-0feae6186757</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nav_item_5&quot;)/a[1]</value>
      <webElementGuid>8fd52185-0182-4c91-a16d-3db2e1ef8bd7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='nav_item_5']/a</value>
      <webElementGuid>95561e9f-e2c3-4355-b8d3-841492058067</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Building Details')]</value>
      <webElementGuid>79979a64-3a81-4f27-a37b-8896c25227fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Applicant Details'])[1]/following::a[1]</value>
      <webElementGuid>eb94555f-da2e-4209-a1ef-5059dc062dcb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Project Details'])[1]/following::a[2]</value>
      <webElementGuid>ca4988d8-3454-407f-8315-12582249b3e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Area Details'])[1]/preceding::a[1]</value>
      <webElementGuid>8bad675c-73a2-4975-8f89-4a1c180049f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Project Library'])[1]/preceding::a[2]</value>
      <webElementGuid>8de315cf-48dd-4944-9e85-e8cf471b9690</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Building Details']/parent::*</value>
      <webElementGuid>b175e69b-0ef5-4272-ac44-ff8666aaee4f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/BPAMSCLIENT2/Pages/WingDetails.aspx')]</value>
      <webElementGuid>810efa31-bb56-4716-9c61-29aec96da3d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//nav/ul/li[3]/a</value>
      <webElementGuid>cf11288d-0cf1-45d3-90f1-dc9bc08635af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/BPAMSCLIENT2/Pages/WingDetails.aspx' and (text() = 'Building Details' or . = 'Building Details')]</value>
      <webElementGuid>441f0f18-71f2-4f7e-aaf9-878c3a08e330</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
