<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Project Library</name>
   <tag></tag>
   <elementGuidId>2e15e6ce-adc3-4803-9f62-dabe767d537f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#nav_item_6 > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='nav_item_6']/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>0a709033-5417-467e-ba8c-980f4f2d4264</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/BPAMSCLIENT2/Pages/Project_Library.aspx</value>
      <webElementGuid>4abfaaeb-cf64-4fa1-8ebe-6c1f6cce9918</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Project Library</value>
      <webElementGuid>dc33c4db-0334-4dca-96cb-a1e35c79a580</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nav_item_6&quot;)/a[1]</value>
      <webElementGuid>e362adbf-2b23-4276-a9bf-910f46999f51</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='nav_item_6']/a</value>
      <webElementGuid>4e475e12-0a4e-48e2-a699-4d521230710c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Project Library')]</value>
      <webElementGuid>4fbf95db-6bd3-453e-8200-410b4e72c188</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Area Details'])[1]/following::a[1]</value>
      <webElementGuid>1cebb633-eae6-415d-8d02-7c3bbf0905a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Building Details'])[1]/following::a[2]</value>
      <webElementGuid>5af37eec-d2de-4798-89f4-33ee79a0f738</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='BG Details'])[1]/preceding::a[1]</value>
      <webElementGuid>9c6591ac-1f80-4cc5-b027-e6cdbc47e086</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Project Library']/parent::*</value>
      <webElementGuid>08f8a78e-5b54-4f43-9c32-4ef6daa8e001</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/BPAMSCLIENT2/Pages/Project_Library.aspx')]</value>
      <webElementGuid>049848a2-54e6-43ad-9ac9-01c1a7cc520c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[5]/a</value>
      <webElementGuid>8c52298a-e3fc-470f-a592-199a983c53a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/BPAMSCLIENT2/Pages/Project_Library.aspx' and (text() = 'Project Library' or . = 'Project Library')]</value>
      <webElementGuid>95faf040-c1dc-4fb1-938b-a20c8afa8ac6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
