<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Project Info</name>
   <tag></tag>
   <elementGuidId>f69c4df6-7487-41ff-967a-e9d22204e9e1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#tabCAF > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='tabCAF']/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>c797c623-d76c-4647-8ed9-508560382889</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#CAF</value>
      <webElementGuid>d3f3cb1f-1472-48b2-8a36-5a541b925b19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>CAF</value>
      <webElementGuid>ad6afe00-feee-487d-bd44-743f50f51d6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>tab</value>
      <webElementGuid>02aa4a8b-5062-4c1c-81ca-acc4a8f8f07f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>tab</value>
      <webElementGuid>4a2255ab-bea7-4868-8103-12b8d069555e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Project Info</value>
      <webElementGuid>55c30512-7f93-432c-b37b-6553050999bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tabCAF&quot;)/a[1]</value>
      <webElementGuid>9d680285-1a8b-43f8-916a-844d8619cdd7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='tabCAF']/a</value>
      <webElementGuid>04b67b13-00dd-428c-9ad8-6084b58c404c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Project Info')]</value>
      <webElementGuid>9753b6de-1528-4f8f-9035-0cc66bfcc5bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Save Plot Details'])[1]/following::a[1]</value>
      <webElementGuid>8f88c3ac-4b1b-4ecc-94a9-ac70ebccdd68</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='View Plot Details'])[1]/following::a[2]</value>
      <webElementGuid>d77f423e-a96b-4b81-8618-cef63ddece7a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Please wait.....'])[1]/preceding::a[1]</value>
      <webElementGuid>59745f4a-b8eb-4870-a605-4024c5c9d842</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='File No.'])[1]/preceding::a[1]</value>
      <webElementGuid>f24608a7-229b-4cb4-83b5-922bc0346844</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Project Info']/parent::*</value>
      <webElementGuid>b2ac944e-9348-4cb8-ade2-deabf43b20df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '#CAF')]</value>
      <webElementGuid>20469808-7ba1-49c8-bacc-a6967cc45074</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/ul/li[4]/a</value>
      <webElementGuid>3fb00f8a-a7b5-4946-970d-856e439e469b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#CAF' and (text() = 'Project Info' or . = 'Project Info')]</value>
      <webElementGuid>e09f7106-063d-4352-8bff-f8bb9e03fc70</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
