<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Save Plot Details</name>
   <tag></tag>
   <elementGuidId>34a8d392-5f67-4b3d-9c21-8dcdb989618b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ancPlot</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='ancPlot']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>bde5bfcf-3e5a-417e-a5c1-04f53395a069</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#divActualGIS</value>
      <webElementGuid>3131640b-b97e-4411-9f84-adce7bf8bb02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ancPlot</value>
      <webElementGuid>a5df95a1-97b7-4185-8130-330d32e93204</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>tab</value>
      <webElementGuid>4bbf1b72-4664-4a86-aeeb-f3ac341622d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>tab</value>
      <webElementGuid>f4bcf4d4-8837-48d5-b8d8-f576f91b7924</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Save Plot Details</value>
      <webElementGuid>877405d8-b192-49fd-9dfe-0c912d0f8427</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ancPlot&quot;)</value>
      <webElementGuid>594c8e20-4cf0-414d-872a-5de4cd34295b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='ancPlot']</value>
      <webElementGuid>5482dd18-d2e7-4b53-87c7-fd7c6c1ddf22</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='tabSavepd']/a</value>
      <webElementGuid>adadebad-2ba6-43f0-8096-98155db81a00</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Save Plot Details')]</value>
      <webElementGuid>a8291898-c43b-4001-86f1-dd20d6abec93</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='View Plot Details'])[1]/following::a[1]</value>
      <webElementGuid>3c56155d-ffcd-4977-82fc-555de9e05b8b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select Your Plot'])[1]/following::a[2]</value>
      <webElementGuid>c0b7d8e4-642a-4b74-a418-f4a72117fe5c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Project Info'])[1]/preceding::a[1]</value>
      <webElementGuid>9a711175-30e5-4e82-8329-06ff21c16382</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Please wait.....'])[1]/preceding::a[2]</value>
      <webElementGuid>9a0051d7-2929-46f1-a3b9-b0af52826de5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Save Plot Details']/parent::*</value>
      <webElementGuid>46050987-6d85-46b8-a495-d3971f3094b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '#divActualGIS')]</value>
      <webElementGuid>47c671c1-26da-4338-8c2d-f08b56696c3b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/ul/li[3]/a</value>
      <webElementGuid>7402efcb-f625-4798-b905-3734e9fb1d1e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#divActualGIS' and @id = 'ancPlot' and (text() = 'Save Plot Details' or . = 'Save Plot Details')]</value>
      <webElementGuid>ff3455cf-991d-4a74-b5bd-e3d63cb947df</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
