<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_OK_1_2_3_4_5</name>
   <tag></tag>
   <elementGuidId>e565e7ae-c8c5-496b-8c75-fe7d21a8310c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#250b2922-3a6e-4fd6-a6e8-c072424ee8a8</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='250b2922-3a6e-4fd6-a6e8-c072424ee8a8']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>a9a0c68b-2a4e-47c2-874e-d1c37b6f8112</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-default</value>
      <webElementGuid>66577a69-b3d1-4052-9c43-a3e10909ef84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>250b2922-3a6e-4fd6-a6e8-c072424ee8a8</value>
      <webElementGuid>20eb4c19-678a-45c4-9ddd-6ba08a8353d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>OK</value>
      <webElementGuid>0f03c369-d53d-43ab-8668-3bef04245ecf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;250b2922-3a6e-4fd6-a6e8-c072424ee8a8&quot;)</value>
      <webElementGuid>066278d1-a8b7-4d41-b98e-1fd086dfbf81</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='250b2922-3a6e-4fd6-a6e8-c072424ee8a8']</value>
      <webElementGuid>b4430bd5-9a15-428b-b6f2-2a6f6547f7db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='354aee00-6a21-4a9e-8cb6-1a6c65c2d944']/div/div/div[3]/div/div/button</value>
      <webElementGuid>942f965f-219c-42f9-a9d3-e5359967a94a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Building Details Saved Successfully.'])[1]/following::button[1]</value>
      <webElementGuid>baa830ec-924f-44a8-abc0-2fa22a600f53</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Information'])[1]/following::button[1]</value>
      <webElementGuid>592715c8-0663-474b-8e12-a2957a1b6904</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='OK']/parent::*</value>
      <webElementGuid>c83935b6-8fd1-43ae-acd3-3676a7d97fe7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div[3]/div/div/button</value>
      <webElementGuid>6dc8dae0-11c7-44e5-81e5-26171b73d516</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = '250b2922-3a6e-4fd6-a6e8-c072424ee8a8' and (text() = 'OK' or . = 'OK')]</value>
      <webElementGuid>fe49e828-bfb1-4a48-b6a8-ee48418a948b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
