<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_OK_1_2_3_4</name>
   <tag></tag>
   <elementGuidId>712545bc-a648-4a70-9f27-def425792e7b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#0990a12c-333a-4af9-a27b-b76b503b5eea</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='0990a12c-333a-4af9-a27b-b76b503b5eea']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>89775678-a327-4656-8a45-51fb0b104b42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-default</value>
      <webElementGuid>0868ee1e-a810-4f6b-b021-d76877250353</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>0990a12c-333a-4af9-a27b-b76b503b5eea</value>
      <webElementGuid>b72be9cb-abbf-4654-8578-2ad758c685ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>OK</value>
      <webElementGuid>c59c8797-3449-4af5-9e0d-b96f56379948</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;0990a12c-333a-4af9-a27b-b76b503b5eea&quot;)</value>
      <webElementGuid>a1fd85c7-4abe-4377-9435-a654e43e2cc8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='0990a12c-333a-4af9-a27b-b76b503b5eea']</value>
      <webElementGuid>542278cd-6a72-4157-82c2-d5b310e45f3e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='4113b426-01c8-4d65-b275-c27ee10cdd26']/div/div/div[3]/div/div/button</value>
      <webElementGuid>f5a1c92d-a6a3-4257-bb4a-32b207f4a5d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Data saved successfully'])[1]/following::button[1]</value>
      <webElementGuid>e2515c11-720a-439b-b360-362be5cec8fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Information'])[1]/following::button[1]</value>
      <webElementGuid>9c52257d-9aed-410b-9c7b-cd7ea0a085c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='OK']/parent::*</value>
      <webElementGuid>0493cfb9-dc8d-4292-a146-4f9da563da9d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div[3]/div/div/button</value>
      <webElementGuid>237ca1af-f77d-47bc-8609-d8893b155d1b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = '0990a12c-333a-4af9-a27b-b76b503b5eea' and (text() = 'OK' or . = 'OK')]</value>
      <webElementGuid>eaed1a53-7a99-4dcb-a72c-c5538e9527a8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
