<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_OK_1_2_3_4_5_6_7_8_9</name>
   <tag></tag>
   <elementGuidId>428953c4-1456-43cd-8827-a5608de566d0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#abe11fdd-920f-436e-ae8d-dfb3e3f0ecee</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='abe11fdd-920f-436e-ae8d-dfb3e3f0ecee']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>46a906c7-da69-41e4-aa19-ce2eb4aac503</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-default</value>
      <webElementGuid>d7c63a86-3b64-44bc-95d4-6da2614e6682</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>abe11fdd-920f-436e-ae8d-dfb3e3f0ecee</value>
      <webElementGuid>10707022-743c-4020-93d8-bd1473acb105</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>OK</value>
      <webElementGuid>16474820-5095-4b9e-8aaa-4184acdd85f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;abe11fdd-920f-436e-ae8d-dfb3e3f0ecee&quot;)</value>
      <webElementGuid>be621ca5-600e-4235-9be0-ddf51089c692</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='abe11fdd-920f-436e-ae8d-dfb3e3f0ecee']</value>
      <webElementGuid>4024ef76-4e46-443c-971f-6100ab5532d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='3fda78fb-8d51-4e7a-8608-3cf52e3f0968']/div/div/div[3]/div/div/button</value>
      <webElementGuid>84b40011-5185-4e92-857b-cb70aa93d412</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Successfully submitted..!!'])[1]/following::button[1]</value>
      <webElementGuid>e3995c04-b555-4faf-891d-a3a2480944db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Information'])[1]/following::button[1]</value>
      <webElementGuid>9417e374-2e59-41fc-ac43-4d3d361383ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='OK']/parent::*</value>
      <webElementGuid>e2ea768e-29ac-4aed-9b22-ef6ff46421ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div[3]/div/div/button</value>
      <webElementGuid>ca2aaeff-7eb9-48d6-9d87-676b9a6b4e26</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'abe11fdd-920f-436e-ae8d-dfb3e3f0ecee' and (text() = 'OK' or . = 'OK')]</value>
      <webElementGuid>3a7aaf4c-4928-4687-ba0c-7fda0f11ec9d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
