<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_OK_1_2</name>
   <tag></tag>
   <elementGuidId>a56d5a63-a74b-4990-94a6-ae4021991589</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#73d2dfb9-454e-4a34-8c57-ba5b0fc24efb</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='73d2dfb9-454e-4a34-8c57-ba5b0fc24efb']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>2ca13df9-bbac-4c65-b70c-a60632cc28a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-default</value>
      <webElementGuid>5d15865e-3eb1-4172-a684-045b16c98cc0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>73d2dfb9-454e-4a34-8c57-ba5b0fc24efb</value>
      <webElementGuid>548d45cf-a0dd-40f2-aeb0-665ab5237e51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>OK</value>
      <webElementGuid>c5c28635-e3a5-468c-ab96-eb46fdf96180</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;73d2dfb9-454e-4a34-8c57-ba5b0fc24efb&quot;)</value>
      <webElementGuid>79a8e02f-aa1f-45e7-9ffe-518a0b7c815b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='73d2dfb9-454e-4a34-8c57-ba5b0fc24efb']</value>
      <webElementGuid>57b2d7ef-79d7-44d0-81f6-2a01055a3395</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='3aefcbc3-8456-47e8-9817-2e01903f46aa']/div/div/div[3]/div/div/button</value>
      <webElementGuid>5b0b5f70-12e7-4d9a-a871-1c7db5e57e65</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Information'])[1]/following::button[1]</value>
      <webElementGuid>afd39330-748c-41e8-b102-31e51d8814fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='×'])[4]/following::button[1]</value>
      <webElementGuid>a6e87e2c-e77a-4d10-b639-3bdca197a891</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='OK']/parent::*</value>
      <webElementGuid>0d85ac32-ea9b-4ce3-80a3-312e8df2c903</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div[3]/div/div/button</value>
      <webElementGuid>836992e4-8f78-42c1-8d8a-503d39e00567</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = '73d2dfb9-454e-4a34-8c57-ba5b0fc24efb' and (text() = 'OK' or . = 'OK')]</value>
      <webElementGuid>1a11d70e-46b8-4d25-8839-9d7d057d888c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
