<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_OK_1_2_3</name>
   <tag></tag>
   <elementGuidId>58d9347a-3402-48f2-95eb-97950fc2ce2d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#98dae626-e307-40a8-858c-292e242b0b65</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='98dae626-e307-40a8-858c-292e242b0b65']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>62d0dedd-5d39-4b0d-bfa7-87d56efda691</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-default</value>
      <webElementGuid>b2f0dc02-78c9-4f45-baf4-f7cc026d3ed4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>98dae626-e307-40a8-858c-292e242b0b65</value>
      <webElementGuid>13d986e1-2a57-48c7-b21c-3206247957ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>OK</value>
      <webElementGuid>b74aa03d-365a-49c1-b269-6b49e9b4a40e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;98dae626-e307-40a8-858c-292e242b0b65&quot;)</value>
      <webElementGuid>0ccefc12-77eb-483c-8d4c-0426b07cbf8e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='98dae626-e307-40a8-858c-292e242b0b65']</value>
      <webElementGuid>d24fb76a-b147-4ec1-a73f-cfd75c5d851d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='1a822dfb-c377-4287-a7b3-1ee164a2f010']/div/div/div[3]/div/div/button</value>
      <webElementGuid>c84ee6c6-89d7-4cdd-9983-b2a984ebac5b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Data saved successfully'])[1]/following::button[1]</value>
      <webElementGuid>780f3799-411d-4710-855d-6876a46bbab9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Information'])[1]/following::button[1]</value>
      <webElementGuid>955acd14-00b5-4350-8f82-85693b2aa2e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='OK']/parent::*</value>
      <webElementGuid>cd6e6b9c-43f5-4355-a1cf-49de70d42745</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div[3]/div/div/button</value>
      <webElementGuid>5405fda3-b0b5-4ced-b941-68dfb181193c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = '98dae626-e307-40a8-858c-292e242b0b65' and (text() = 'OK' or . = 'OK')]</value>
      <webElementGuid>2eb5c690-43c9-45c7-a0e2-53dc83006bf6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
