<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_OK</name>
   <tag></tag>
   <elementGuidId>11faffe1-5b98-451e-8909-32cd4d527289</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#8d4ffabf-b580-4e48-9788-03116847526a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='8d4ffabf-b580-4e48-9788-03116847526a']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>9efebc0b-e680-41df-a299-83e7a8d54600</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-default</value>
      <webElementGuid>3f6af7aa-072a-4701-a24b-74830de6a1be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>8d4ffabf-b580-4e48-9788-03116847526a</value>
      <webElementGuid>416ca00c-4c8a-4e0d-b37b-5f76ede303bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>OK</value>
      <webElementGuid>10a1ca03-1a3c-47cc-b7af-ba46f701b974</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;8d4ffabf-b580-4e48-9788-03116847526a&quot;)</value>
      <webElementGuid>b933e48d-2d0b-4e0e-baa2-fc392af67f0e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='8d4ffabf-b580-4e48-9788-03116847526a']</value>
      <webElementGuid>88f25f82-f541-4f58-8789-79bfeff5b4e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='25d3734d-1448-4251-8f14-318eed938282']/div/div/div[3]/div/div/button</value>
      <webElementGuid>8ed729cb-1e5f-4f5f-b9ce-2e677a84d47a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='It seems that you have not selected any village.'])[1]/following::button[1]</value>
      <webElementGuid>90e09d64-b813-4a26-9d4f-983ca8d3252e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Information'])[1]/following::button[1]</value>
      <webElementGuid>8e2d6b0d-3f5b-42eb-a8aa-33de96f0225e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='OK']/parent::*</value>
      <webElementGuid>22dc2895-e7f3-46a9-a902-b35b7d4898df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div[3]/div/div/button</value>
      <webElementGuid>60ae1675-7af1-42f7-8abf-9bf24873bcdd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = '8d4ffabf-b580-4e48-9788-03116847526a' and (text() = 'OK' or . = 'OK')]</value>
      <webElementGuid>05e40fc3-2127-465d-a6b7-2302bb018a78</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
