<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_OK_1_2_3_4_5_6_7_8</name>
   <tag></tag>
   <elementGuidId>166c3f67-578f-4e74-b7e6-6b53ee84217f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#f96fbc21-71c2-4b2a-8d81-5dd7807dcdfa</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='f96fbc21-71c2-4b2a-8d81-5dd7807dcdfa']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>17f73547-0e8e-4cc1-a610-38e07b0030f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-default</value>
      <webElementGuid>70e4e5c4-16d7-4427-8272-a064ed6d3d4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>f96fbc21-71c2-4b2a-8d81-5dd7807dcdfa</value>
      <webElementGuid>5f6c0757-36c5-43a0-9c9a-e5c0e40942a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>OK</value>
      <webElementGuid>bf19333d-acfe-401f-979b-9da77e4faecf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;f96fbc21-71c2-4b2a-8d81-5dd7807dcdfa&quot;)</value>
      <webElementGuid>dae08567-766d-4801-b443-3fac5d1f34a5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='f96fbc21-71c2-4b2a-8d81-5dd7807dcdfa']</value>
      <webElementGuid>292b72be-825b-484c-93bd-e6216b3cff0d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='7b7ce336-2887-4880-9bc8-9c1110cc630e']/div/div/div[3]/div/div/button</value>
      <webElementGuid>2d9daee4-7712-434b-9738-2cc378318d33</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='BG acceptance saved successfully.'])[1]/following::button[1]</value>
      <webElementGuid>31e2f222-560b-4b07-aef6-1e011c584f20</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Information'])[1]/following::button[1]</value>
      <webElementGuid>8e428d3b-1927-40ab-8ef9-c18c68e15531</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='OK']/parent::*</value>
      <webElementGuid>5b15615b-a183-464d-8c18-5021ed41bf0d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div[3]/div/div/button</value>
      <webElementGuid>28bc54d5-44ce-4f5c-ad9d-2abd83a7ee1a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'f96fbc21-71c2-4b2a-8d81-5dd7807dcdfa' and (text() = 'OK' or . = 'OK')]</value>
      <webElementGuid>b0e54f20-a68a-4a3d-8528-96ecbe55e01a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
