<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_OK_1_2_3_4_5_6</name>
   <tag></tag>
   <elementGuidId>24902528-1a4f-42a9-a3f8-f4b09624769b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#14b10ae2-abcd-4a39-afca-7ba0b7455a6c</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='14b10ae2-abcd-4a39-afca-7ba0b7455a6c']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>780a0d43-331f-4407-b8a7-8f2785319349</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-default</value>
      <webElementGuid>3331dcda-97cd-43c5-9ca0-f61fa6632375</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>14b10ae2-abcd-4a39-afca-7ba0b7455a6c</value>
      <webElementGuid>85ac3c56-eb78-4fce-8b9b-43b48f61c131</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>OK</value>
      <webElementGuid>4b252ac7-eab1-445a-ad5e-e598a621ae34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;14b10ae2-abcd-4a39-afca-7ba0b7455a6c&quot;)</value>
      <webElementGuid>7aac8ec3-af0b-4a09-a8f2-344ff9a6e479</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='14b10ae2-abcd-4a39-afca-7ba0b7455a6c']</value>
      <webElementGuid>0b48e53c-6f7f-42e8-b234-a7823f9b0128</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='8f03eba1-2998-46d5-b211-b84b3d01c937']/div/div/div[3]/div/div/button</value>
      <webElementGuid>bb718ff8-37e9-46a1-b04f-f2652a50192a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Data Saved Successfully'])[1]/following::button[1]</value>
      <webElementGuid>b743bad1-f8cb-4cf5-81bb-4df589dabf90</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Information'])[1]/following::button[1]</value>
      <webElementGuid>553855c0-597c-4aff-b5ed-316928db6b92</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='OK']/parent::*</value>
      <webElementGuid>49053632-6f36-43c7-ae7b-0d9591237308</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div[3]/div/div/button</value>
      <webElementGuid>4cd2abfc-0998-4ac2-9e69-3462d6119739</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = '14b10ae2-abcd-4a39-afca-7ba0b7455a6c' and (text() = 'OK' or . = 'OK')]</value>
      <webElementGuid>b3ec2d2a-e309-4c8e-862f-6f1c2e4713a3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
