<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_OK_1</name>
   <tag></tag>
   <elementGuidId>d778a8c0-55b6-4876-9907-f5359c013e67</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#95b97d7b-576a-443d-adf6-ba64c360ede4</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='95b97d7b-576a-443d-adf6-ba64c360ede4']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>01cc8f14-083e-4b6c-841d-bbf8e829f3ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-default</value>
      <webElementGuid>e71e0881-d25d-403e-8dae-5287325926cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>95b97d7b-576a-443d-adf6-ba64c360ede4</value>
      <webElementGuid>f204256c-a2f6-4087-ba1f-7cd0280c11a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>OK</value>
      <webElementGuid>33c80c06-8910-4097-b6d0-58fe28afbc5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;95b97d7b-576a-443d-adf6-ba64c360ede4&quot;)</value>
      <webElementGuid>eddd26f5-33bc-4295-9a70-fdf7e81ff935</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='95b97d7b-576a-443d-adf6-ba64c360ede4']</value>
      <webElementGuid>0f309ae0-4a0e-4d50-9b05-59709b7cfb97</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cc93d6de-87ae-493e-a5a6-fc3621281071']/div/div/div[3]/div/div/button</value>
      <webElementGuid>c32ea61f-1256-4251-832b-46b80f72f74f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Please save plot details first.'])[1]/following::button[1]</value>
      <webElementGuid>582280e0-37f7-402f-b618-713233ede899</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Information'])[1]/following::button[1]</value>
      <webElementGuid>6befbd6e-4a52-4417-b543-976c844dc3c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='OK']/parent::*</value>
      <webElementGuid>a88f097a-432b-4795-b3f0-306c8d93cf3e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div[3]/div/div/button</value>
      <webElementGuid>6410ee26-ef29-46eb-9699-15d62d1e5570</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = '95b97d7b-576a-443d-adf6-ba64c360ede4' and (text() = 'OK' or . = 'OK')]</value>
      <webElementGuid>0e918886-a862-4302-999d-e3d60c4183d3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
