<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_OK_1_2_3_4_5_6_7</name>
   <tag></tag>
   <elementGuidId>ae6dd982-440b-4918-82cb-d6603d6ce70f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#452c522b-aec3-4eb4-9006-532da500aab2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='452c522b-aec3-4eb4-9006-532da500aab2']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>87e070c5-69a2-4c2e-a7b7-77f4db8c2dec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-default</value>
      <webElementGuid>c0f6f4c3-914a-42af-b8dc-f7660e432b94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>452c522b-aec3-4eb4-9006-532da500aab2</value>
      <webElementGuid>6b94cf9a-1a9c-4041-a5b5-66d42ce5d6f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>OK</value>
      <webElementGuid>7461c10c-2dd2-434f-91b3-bbb11225b964</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;452c522b-aec3-4eb4-9006-532da500aab2&quot;)</value>
      <webElementGuid>5badd1fa-5186-4f8e-8dfa-eb8b6f8e11c1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='452c522b-aec3-4eb4-9006-532da500aab2']</value>
      <webElementGuid>7189667e-37cc-4d21-9017-4b4370ab5acb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='3dd90baf-f6fb-49ec-895a-456481dfdca1']/div/div/div[3]/div/div/button</value>
      <webElementGuid>8c436473-f3c2-4afe-af29-bb104fe27271</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='BG deatails saved successfully.!'])[1]/following::button[1]</value>
      <webElementGuid>3e1ebfbb-8d83-4882-abdb-9ee336f5c2ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Information'])[1]/following::button[1]</value>
      <webElementGuid>e367569f-bf77-4e56-a58a-6bfb3d471051</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='OK']/parent::*</value>
      <webElementGuid>464a2838-b217-4bfc-b41b-eabc15b6c500</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div[3]/div/div/button</value>
      <webElementGuid>91c2289a-032e-428a-a174-601185db1d12</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = '452c522b-aec3-4eb4-9006-532da500aab2' and (text() = 'OK' or . = 'OK')]</value>
      <webElementGuid>b439b126-d5cc-4670-9c49-01fbea713b2f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
