<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Least Area_ucAreaRptAreaDetailsctl01r_823ecd</name>
   <tag></tag>
   <elementGuidId>1f467541-5910-4e05-be52-85bcf1d67afc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ucArea_RptAreaDetails_rptPlotExt_0_txt712_0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ucArea_RptAreaDetails_rptPlotExt_0_txt712_0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>bdb783f0-0255-4025-9a69-250514401641</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ucArea$RptAreaDetails$ctl01$rptPlotExt$ctl01$txt712</value>
      <webElementGuid>b3fa7400-74bc-4b17-8c75-9b0a3e57afea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>5c4267d5-e0bd-426d-b4c4-ce5ba0d22774</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>01d77f94-e6ae-4e07-9bf9-f59da4a2618f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>09242828-8de6-47b9-bbe1-ff84b18866d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>javascript:setTimeout('__doPostBack(\'ucArea$RptAreaDetails$ctl01$rptPlotExt$ctl01$txt712\',\'\')', 0)</value>
      <webElementGuid>ec16081f-6dcc-4022-9191-22fe0378d96a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>if (WebForm_TextBoxKeyHandler(event) == false) return false;</value>
      <webElementGuid>d32085b6-1eac-4bb4-ab0e-b14a1d5d7cbb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ucArea_RptAreaDetails_rptPlotExt_0_txt712_0</value>
      <webElementGuid>cb33b8fe-77d5-400c-8096-7fd44330fd7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter</value>
      <webElementGuid>f2b559ea-26bc-4c07-b9a6-4e55e3c4b131</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ucArea_RptAreaDetails_rptPlotExt_0_txt712_0&quot;)</value>
      <webElementGuid>bb417989-ea80-4a1a-b27e-4b27d55ef614</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ucArea_RptAreaDetails_rptPlotExt_0_txt712_0']</value>
      <webElementGuid>bbbd767e-7556-46ff-b468-ce67433ef0fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='POITable0']/tbody/tr/td[2]/input</value>
      <webElementGuid>b4c40a38-ab04-4ac7-a308-ade2914a2138</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/input</value>
      <webElementGuid>c89ed548-0c5c-45a4-b961-53650a82c462</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'ucArea$RptAreaDetails$ctl01$rptPlotExt$ctl01$txt712' and @type = 'text' and @id = 'ucArea_RptAreaDetails_rptPlotExt_0_txt712_0' and @placeholder = 'Enter']</value>
      <webElementGuid>343bcef7-1a45-4d46-b911-67205fb1bc1a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
