<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_BG Number_ctl00PageContenttxtBGNumber</name>
   <tag></tag>
   <elementGuidId>c02f7d9f-8068-4b21-bb8c-7ce74c377ea1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#PageContent_txtBGNumber</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='PageContent_txtBGNumber']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f3cc2839-aab0-4083-9f84-1e6d6ef8d07d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$PageContent$txtBGNumber</value>
      <webElementGuid>10e25c8b-4251-4e48-a5a5-ef6f4b6d9978</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>3096a117-b707-43e5-bb01-4517c7e201dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>PageContent_txtBGNumber</value>
      <webElementGuid>01d5dfef-9f7b-49c4-b27d-9ac229ea5f32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>a6b2821e-3b2d-423a-9927-0532852eeaf2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>76270adf-a81d-4c26-9916-67a01f8ef2d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;PageContent_txtBGNumber&quot;)</value>
      <webElementGuid>516a7f4c-7c9b-418e-a7fe-87b63c6f36b4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='PageContent_txtBGNumber']</value>
      <webElementGuid>623ec5f1-2498-4d4c-bd7f-7689c4e72795</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='PageContent_BGDiv']/div[3]/div/input</value>
      <webElementGuid>8dbb2d3c-f2df-478a-8b8c-436f18221617</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[3]/div/input</value>
      <webElementGuid>b8d3eefb-21ce-4490-9c22-11c36f672bea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'ctl00$PageContent$txtBGNumber' and @type = 'text' and @id = 'PageContent_txtBGNumber']</value>
      <webElementGuid>0a4fdc83-904e-488b-8483-8dec3aa069ce</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
