<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Bank Name_ctl00PageContenttxtBankNumber</name>
   <tag></tag>
   <elementGuidId>7fe76ed9-7d91-41af-a007-94b99677926e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#PageContent_txtBankNumber</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='PageContent_txtBankNumber']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7c9ee71f-d1d7-4067-9e96-3c86e898f08f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$PageContent$txtBankNumber</value>
      <webElementGuid>746ea5ae-4fe0-4a0d-8a4e-79a0b4069fab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>d6e67c2a-bea4-47d4-a424-5d05fa84b77e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>PageContent_txtBankNumber</value>
      <webElementGuid>fc3f4363-fe07-49f7-b53e-3870165e44e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>3f60cb75-eeb0-4bda-9f9a-f48fc124eb2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>43c9297c-1446-445e-aad5-c2ebb6ad4b80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;PageContent_txtBankNumber&quot;)</value>
      <webElementGuid>43d17f6f-960c-497f-99a8-51b4504a97d4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='PageContent_txtBankNumber']</value>
      <webElementGuid>37dce3b5-6929-4e48-900b-562bdc241fd6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='PageContent_BGDiv']/div[4]/div/input</value>
      <webElementGuid>de5c76d2-fb48-4707-a2da-963aa1c79a21</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[4]/div/input</value>
      <webElementGuid>ec9c0c93-eb06-4c33-88c5-cb666049e6c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'ctl00$PageContent$txtBankNumber' and @type = 'text' and @id = 'PageContent_txtBankNumber']</value>
      <webElementGuid>e16b90ae-d7c8-4558-86b1-e075882175ec</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
