<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_CREATE PROJECT_ctl00nav_leftbtnsubmitproject</name>
   <tag></tag>
   <elementGuidId>f01745ee-b7eb-4418-bd94-040c37061a5c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#nav_left_btnsubmitproject</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='nav_left_btnsubmitproject']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f1c55cf3-0bb6-4a11-ae72-322dedd1da94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>return CheckProjectSubmission(); if (typeof(Page_ClientValidate) == 'function') Page_ClientValidate(''); </value>
      <webElementGuid>323d741d-61e9-47a8-8af5-26d14cabec7e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$nav_left$btnsubmitproject</value>
      <webElementGuid>5af08f36-d59a-48ff-9c2a-bd7d67c52489</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>e11da614-7ac6-427c-979b-46afec518aaa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>nav_left_btnsubmitproject</value>
      <webElementGuid>452135e8-e557-467c-a0e2-84fd4883f648</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Submit Project</value>
      <webElementGuid>44678ae5-6280-4d84-9e44-c9734a904808</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary</value>
      <webElementGuid>716665c9-ef61-4ef3-9a37-1854c8ddfe72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nav_left_btnsubmitproject&quot;)</value>
      <webElementGuid>c7863c3b-fd68-4d9a-97c8-7ab7e3a381f1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='nav_left_btnsubmitproject']</value>
      <webElementGuid>227299a1-d4bb-4aa2-9a4b-152fb9c62ccc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='nav_left_divButtons']/div[2]/input</value>
      <webElementGuid>781b8ae4-cd81-4228-8345-a96c2741b89c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//nav/div/div[2]/input</value>
      <webElementGuid>bf3aaaae-b933-4f73-91e1-aed9ac05e037</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'ctl00$nav_left$btnsubmitproject' and @type = 'submit' and @id = 'nav_left_btnsubmitproject']</value>
      <webElementGuid>787e231e-e5b3-4474-90a9-8f5c3479d5ce</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
