<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__txtGrossPlotArea</name>
   <tag></tag>
   <elementGuidId>85480da0-be99-46c7-bb9b-88d602b7d64b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#txtGrossPlotArea</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtGrossPlotArea']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b3b219dd-007b-4de5-ac6f-e8784c31a44f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>txtGrossPlotArea</value>
      <webElementGuid>38f43f45-30dc-484b-b8c5-52cc68550502</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>2b7d5e1c-e319-4061-bdc5-ed06245a1e09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtGrossPlotArea</value>
      <webElementGuid>af5a9201-8009-4183-98aa-e6866b542909</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>1649bd32-3229-4332-a145-8751900cea5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>return ValidateNumbers(event)</value>
      <webElementGuid>726a08b0-3a25-4b04-b7fe-71344b5bcd7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>validategrossplotarea()</value>
      <webElementGuid>f1556546-8df5-4ba1-93f4-41d5b66d0a04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtGrossPlotArea&quot;)</value>
      <webElementGuid>cc275992-5296-4002-b090-900c48b180b9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtGrossPlotArea']</value>
      <webElementGuid>def246d2-bcea-4c74-a171-3c408257dc9d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='accordion']/div[2]/div/div[3]/div/input</value>
      <webElementGuid>0715ad23-f17d-4173-9904-5010e3743c88</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/input</value>
      <webElementGuid>ffd1c8af-c262-468f-b4d1-95c63fc9681c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'txtGrossPlotArea' and @type = 'text' and @id = 'txtGrossPlotArea']</value>
      <webElementGuid>ca541796-7d21-4050-ba55-1acf2b6e2760</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
