<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_SAC No_txtSACNO</name>
   <tag></tag>
   <elementGuidId>99d5cf60-6869-4dc6-9f29-e9a7b6c65ba4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#txtSACNO</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtSACNO']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9f1b1fbc-85de-4572-8f3f-b96b89b557d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>txtSACNO</value>
      <webElementGuid>c3d86798-08ca-4d36-af5c-1b37cd90b705</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>265b7063-e510-4894-8264-901ce402be39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtSACNO</value>
      <webElementGuid>a3165e30-820a-44e6-a04e-786958098783</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>ecd7bc9b-87cd-4cae-b1a8-3ced3efb3436</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtSACNO&quot;)</value>
      <webElementGuid>cd6635a4-9882-4c3c-ba8b-252d00a3003d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtSACNO']</value>
      <webElementGuid>f9059615-2909-4ed0-b3a6-0324c942f15e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='divSDA']/input</value>
      <webElementGuid>e9da7cd5-edf7-44d0-8718-8d58dadeb4bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/input</value>
      <webElementGuid>214ad51c-ae55-460b-a4d5-88210f8c98e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'txtSACNO' and @type = 'text' and @id = 'txtSACNO']</value>
      <webElementGuid>0c8e17bc-179a-4a90-a85e-92c672934871</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
