<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_BG Date_ctl00PageContenttxtBGDate</name>
   <tag></tag>
   <elementGuidId>765709af-b4f4-468c-b0de-ed37af3251e1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#PageContent_txtBGDate</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='PageContent_txtBGDate']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6451e412-8f50-47fa-b6be-6bef8697e34f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$PageContent$txtBGDate</value>
      <webElementGuid>46a84bbe-4a4a-4874-9949-e144e1e41f49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>15e63593-f272-4a76-8479-8d215ee7c254</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>PageContent_txtBGDate</value>
      <webElementGuid>43115373-fa53-45e8-9a5e-7a81c7695a19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>6fe85485-3660-4e60-a057-9d2704f14657</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>a210e3a8-223e-4b32-9066-9af1c3c69837</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>MM-DD-YYYY</value>
      <webElementGuid>0c611096-fe20-437a-bacf-ca1e4aa05b01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;PageContent_txtBGDate&quot;)</value>
      <webElementGuid>68972993-d24e-4213-99f9-1ed59a002a96</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='PageContent_txtBGDate']</value>
      <webElementGuid>5813a9cb-b40a-4933-80b6-3c4175b1320c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='PageContent_BGDiv']/div[3]/div[2]/input</value>
      <webElementGuid>a6b154fe-40a3-42dc-bae5-9835b2162130</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[3]/div[2]/input</value>
      <webElementGuid>9a1b27af-6344-4ae4-9bc1-676a053e44ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'ctl00$PageContent$txtBGDate' and @type = 'text' and @id = 'PageContent_txtBGDate' and @placeholder = 'MM-DD-YYYY']</value>
      <webElementGuid>c6e08632-8e39-48e5-949f-2cb6061c3b09</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
