<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__addRow</name>
   <tag></tag>
   <elementGuidId>884029d4-0efe-45dc-bbf7-5d25318dc78e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#addRow</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='addRow']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0b1b7b09-af7d-4c74-b6f4-49b881348a2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>09e39463-538c-4d95-986f-9aef8b8a9787</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-info</value>
      <webElementGuid>e522df77-32eb-46c4-9172-36baa01e75a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>addRow</value>
      <webElementGuid>0373edbf-9a8a-4c42-ad7f-c7b7d7eda473</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>+</value>
      <webElementGuid>2afddf2c-f14d-4b4e-9469-09444e4e96a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>Addnewrow()</value>
      <webElementGuid>73e0b90b-264f-44da-8aa5-80c655450252</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;addRow&quot;)</value>
      <webElementGuid>eaba4c52-dd15-45d5-8941-a4603add0781</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='addRow']</value>
      <webElementGuid>60124a93-8c80-4af9-a66d-06ca55fd6993</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='accordion']/div[2]/div/div/div/input</value>
      <webElementGuid>58a3c7df-5387-409b-ba7a-48e0d9949bea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div[2]/div/div/div/input</value>
      <webElementGuid>7c0cfe44-c6cc-4d12-a845-83c504452196</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button' and @id = 'addRow']</value>
      <webElementGuid>1e8cddf6-f446-4fb3-9290-661eccbc7126</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
