<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Area Details_ucAreaRptAreaDetailsctl0_6bc619</name>
   <tag></tag>
   <elementGuidId>10bcdb68-dc44-4c61-978e-06e06ae67b95</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ucArea_RptAreaDetails_txtOwnernm_0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ucArea_RptAreaDetails_txtOwnernm_0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ba8f98cd-2661-4d2b-b821-44a7d617c3c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ucArea$RptAreaDetails$ctl01$txtOwnernm</value>
      <webElementGuid>970b37e0-e676-45ae-981f-4032b8ca5811</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>5eea1f3d-9d6d-4474-a71b-ea933390ee61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ucArea_RptAreaDetails_txtOwnernm_0</value>
      <webElementGuid>47a38202-b34f-4937-8e4d-fbcb34f51a05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>08147b63-06cb-46d8-a872-080ae56847a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter OwnerName</value>
      <webElementGuid>3907205a-166d-4300-85c8-fa9465331d19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ucArea_RptAreaDetails_txtOwnernm_0&quot;)</value>
      <webElementGuid>00f30cba-eced-4506-8fc1-bc39e3673577</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ucArea_RptAreaDetails_txtOwnernm_0']</value>
      <webElementGuid>a1557612-25e4-4de7-9e81-8a00dcdd12ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='accordion']/div/div/div/div[3]/div/input</value>
      <webElementGuid>31e22d8d-f3f9-47b0-a2cd-1b72726f0189</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/input</value>
      <webElementGuid>849f2fa9-d56d-4157-97d8-a367c6d1b4ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'ucArea$RptAreaDetails$ctl01$txtOwnernm' and @type = 'text' and @id = 'ucArea_RptAreaDetails_txtOwnernm_0' and @placeholder = 'Enter OwnerName']</value>
      <webElementGuid>3a8a07c9-6323-4827-b8d2-182b8ec193e6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
