<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Gross Construction Area (Sq. mtrs.)_A_a70d88</name>
   <tag></tag>
   <elementGuidId>ebd9d9a7-e1e9-412c-94a5-0438e64018ec</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Addbuilding_txt_grossbuiltArea</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Addbuilding_txt_grossbuiltArea']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ffbc535c-c24d-446e-8cc9-cf9484243dd3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Addbuilding$txt_grossbuiltArea</value>
      <webElementGuid>d402198d-bfaa-4640-b883-5a3b54e6dcb4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Addbuilding_txt_grossbuiltArea</value>
      <webElementGuid>a37f61bc-8beb-4655-8984-20de7d8176e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter</value>
      <webElementGuid>f0db0606-67c2-4f4f-9ce4-7aaa222f096d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>2ad8b9fa-7721-4d7e-b899-1c80eeeab8ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>5889455b-f5f3-498d-8826-a1358dec3275</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Addbuilding_txt_grossbuiltArea&quot;)</value>
      <webElementGuid>bfad74e6-6463-4806-b93c-e758f2beb16c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Addbuilding_txt_grossbuiltArea']</value>
      <webElementGuid>ffb1a5dc-e848-4dd7-8d23-4ceac0e7c84f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Addbuilding_div_AddBuilding']/div/div[4]/div/div[2]/input</value>
      <webElementGuid>51b8952b-20f4-4c42-8866-a5a0583219c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div[2]/input</value>
      <webElementGuid>43798eb8-cf0e-4b85-a941-9f3e8b8c26c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'Addbuilding$txt_grossbuiltArea' and @id = 'Addbuilding_txt_grossbuiltArea' and @placeholder = 'Enter' and @type = 'text']</value>
      <webElementGuid>5311ede2-b3dc-401f-ac3a-bd312de84068</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
