<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Proposal is as per_rdbDPPlan</name>
   <tag></tag>
   <elementGuidId>04b1648b-c984-4775-94bc-4491ec615a4e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#rdbDPPlan1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='rdbDPPlan1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>948633cd-e1df-43bd-b2ee-c4683bea96d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>rdbDPPlan1</value>
      <webElementGuid>e37a5bc6-222b-4f5f-9232-7f37d39ed7a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>6ea71917-5db6-49ec-a0e0-b109c5c0f1ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>rdbDPPlan</value>
      <webElementGuid>e012f90d-d76e-4356-a72f-ee23c4fd5ab4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>rdbDPPlan1</value>
      <webElementGuid>54e65561-bc08-4d1f-aa65-57b51ab8d653</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rdbDPPlan1&quot;)</value>
      <webElementGuid>0f5e5178-e9fa-44c0-9187-ec79a00b5425</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='rdbDPPlan1']</value>
      <webElementGuid>64add84b-d64d-4802-8fd3-664e56a9c2ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='accordionCAF']/div[3]/div/div[2]/input</value>
      <webElementGuid>e78cadf6-350d-4675-8255-90b98f109812</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div[2]/input</value>
      <webElementGuid>6427765b-8e99-4196-b294-92900783c8b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'rdbDPPlan1' and @type = 'radio' and @name = 'rdbDPPlan']</value>
      <webElementGuid>b40b5c89-7a36-43d5-9e0c-34672818baf8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
