<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Aadhar No_txtAadharNo</name>
   <tag></tag>
   <elementGuidId>6da237e9-04da-4325-b13d-78736faa0759</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#txtAadharNo</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtAadharNo']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ebf7c18a-b55c-46b3-a51a-53b0fd844d2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>txtAadharNo</value>
      <webElementGuid>ab561eb3-23d7-4688-aa2e-9208c6754602</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>d01ce88c-99af-4329-a968-b632683bfe81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>12</value>
      <webElementGuid>eb5e8181-11d8-4f84-b724-ade75010ba07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtAadharNo</value>
      <webElementGuid>c5f5e4a6-6183-4f3b-be85-ed8e9ff8d6e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>5888a994-8a5c-4027-a404-27f1579f2abc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>fnKeyPress();</value>
      <webElementGuid>19ba9f1a-f553-447f-89e3-8ca4372c3dce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtAadharNo&quot;)</value>
      <webElementGuid>f4db7cca-75fa-4b19-86c3-1ae40c74be12</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtAadharNo']</value>
      <webElementGuid>033cc35d-3b18-4a2f-b49e-4fb6014685b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='divAddDetails']/div[7]/div/div[2]/input</value>
      <webElementGuid>3a9f719a-8bb8-4183-b1df-702adf06b79c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/div[2]/input</value>
      <webElementGuid>dd21e237-d8ab-4917-a7fb-e42225dcc479</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'txtAadharNo' and @type = 'text' and @id = 'txtAadharNo']</value>
      <webElementGuid>3847e873-017e-4b5d-b9d7-838936d97ef3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
