<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Branch Name_ctl00PageContenttxtBranchName</name>
   <tag></tag>
   <elementGuidId>092dbfcd-5b93-4436-ab33-e561c0c25b45</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#PageContent_txtBranchName</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='PageContent_txtBranchName']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b937f6a3-f60a-4ae7-97fe-8ce1e13253d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$PageContent$txtBranchName</value>
      <webElementGuid>50610902-2b4d-40d7-af9d-605dfa8fd164</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>2fec864b-2ef3-418d-9a72-75ecf7d7f5ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>PageContent_txtBranchName</value>
      <webElementGuid>d7dbbeae-5549-4d06-8c93-dbb7df814c45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>7de8cc56-4175-4332-a766-ddd86b5e2c5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>f44c7b30-0e06-4704-ae26-e60747bc72a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;PageContent_txtBranchName&quot;)</value>
      <webElementGuid>8a43bac1-ac47-4ed2-afbf-3084a343a72f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='PageContent_txtBranchName']</value>
      <webElementGuid>63499f28-8643-48e6-962f-7792b5b6d3c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='PageContent_BGDiv']/div[4]/div[2]/input</value>
      <webElementGuid>f8581926-0f05-4d49-acc2-4c39f5a3a071</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[4]/div[2]/input</value>
      <webElementGuid>6ee2dad8-2d5c-4b52-9f61-11e40d6be59e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'ctl00$PageContent$txtBranchName' and @type = 'text' and @id = 'PageContent_txtBranchName']</value>
      <webElementGuid>67069ea3-001c-453b-98af-8e5065aab9dc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
