<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Area Details_ucAreaRptAreaDetailsctl0_e62e63</name>
   <tag></tag>
   <elementGuidId>f525e4df-59cf-4de8-a222-c8c6af582ea5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ucArea_RptAreaDetails_txtPlotName_0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ucArea_RptAreaDetails_txtPlotName_0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f95b473f-4776-4026-ac30-42ed40510850</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ucArea$RptAreaDetails$ctl01$txtPlotName</value>
      <webElementGuid>6eed94d3-93cb-44df-8105-5af4c313fe12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>3a496b37-856e-47a3-9503-305b308af163</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ucArea_RptAreaDetails_txtPlotName_0</value>
      <webElementGuid>586ecbd0-b51a-40d2-ba97-5e38be90112c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>2deeae8f-e4a7-4f7b-8e45-d1c8c8f817ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter PlotName</value>
      <webElementGuid>891bdc9a-b843-4f17-b03f-837e614d5517</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ucArea_RptAreaDetails_txtPlotName_0&quot;)</value>
      <webElementGuid>8b9a50ba-d138-48a4-a953-70f4cd95b16f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ucArea_RptAreaDetails_txtPlotName_0']</value>
      <webElementGuid>fdf6b55b-4707-4fc7-a90a-1d3e79be7d42</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='accordion']/div/div/div/div[2]/div/input</value>
      <webElementGuid>384c8e38-090b-471d-904e-54b311b293aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input</value>
      <webElementGuid>f1617552-f8f3-47fc-85d9-d9e78127f928</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'ucArea$RptAreaDetails$ctl01$txtPlotName' and @type = 'text' and @id = 'ucArea_RptAreaDetails_txtPlotName_0' and @placeholder = 'Enter PlotName']</value>
      <webElementGuid>18f7f30d-0b79-43bb-951e-7ccc32207b06</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
