<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__txtFullNameofApplicant</name>
   <tag></tag>
   <elementGuidId>163a5e76-bdee-43be-bb97-d63a020e677d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#txtFullNameofApplicant</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtFullNameofApplicant']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f6785e61-977f-4618-82cc-2cd8e9e8c1d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>txtFullNameofApplicant</value>
      <webElementGuid>c32f71ae-8c58-43fb-80ce-afa6d9942d50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>e2db8cac-b4ce-428c-b410-de8551c6c0eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>500</value>
      <webElementGuid>366c8d90-7b52-4e32-b3d4-2cd10a38ed97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtFullNameofApplicant</value>
      <webElementGuid>9f3b336b-1c0a-42c8-a3cc-d38fdd1e4269</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>d160b2d9-5d8a-439d-b1be-4685d0486eeb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtFullNameofApplicant&quot;)</value>
      <webElementGuid>3bd0d9db-1659-4be5-9d7d-5a4b067ab5e5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtFullNameofApplicant']</value>
      <webElementGuid>35631be2-8bc2-480c-8780-e2ab965eeed6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='accordionCAF']/div[8]/div/div/input</value>
      <webElementGuid>752f5242-e019-4e99-a553-4972a7baa3de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div/div/input</value>
      <webElementGuid>8133d167-9833-4069-b143-045879f06ee4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'txtFullNameofApplicant' and @type = 'text' and @id = 'txtFullNameofApplicant']</value>
      <webElementGuid>ff543f29-b9f4-4300-bfb0-8998ad03cffa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
