<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_FSI Built up Area (Sq. mtrs.)_Addbuil_32c922</name>
   <tag></tag>
   <elementGuidId>a6197cd0-9777-496d-bccf-683b6f21d95a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Addbuilding_txt_buildArea</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Addbuilding_txt_buildArea']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b9510dfc-2735-4d05-91ef-5ac40df77a96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Addbuilding$txt_buildArea</value>
      <webElementGuid>5758aaed-ccad-429f-a55b-7fde5a2350b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Addbuilding_txt_buildArea</value>
      <webElementGuid>6d045a0a-7a8c-4a19-b0a9-9c236ba4602f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter</value>
      <webElementGuid>f57cc728-f76f-48f5-87bd-86e3f83ca320</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>f7e13edb-6b9e-49fe-9bca-16e49ba5f484</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>412e92f9-6719-49f9-87c1-36d3e6d8afe7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Addbuilding_txt_buildArea&quot;)</value>
      <webElementGuid>9cf9d295-9426-4082-81a4-bcdb499f473a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Addbuilding_txt_buildArea']</value>
      <webElementGuid>1ec0c551-004f-4b6f-8f66-97d1a1dadab3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Addbuilding_div_AddBuilding']/div/div[4]/div/div/input</value>
      <webElementGuid>a7e832ff-8984-4087-b711-6dd78b4c879e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/input</value>
      <webElementGuid>dca62306-4b4c-4a9d-9cbf-b6bedb636abb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'Addbuilding$txt_buildArea' and @id = 'Addbuilding_txt_buildArea' and @placeholder = 'Enter' and @type = 'text']</value>
      <webElementGuid>9c008539-79c0-4d3c-ba4d-ffa958d4b1b8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
