<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_BG Valid Date_ctl00PageContenttxtBGValidDate</name>
   <tag></tag>
   <elementGuidId>7981db3c-5bce-41fa-9c9b-fbdf61048ecc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#PageContent_txtBGValidDate</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='PageContent_txtBGValidDate']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1d4cfd15-9074-44f2-a20a-bfb88f663817</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$PageContent$txtBGValidDate</value>
      <webElementGuid>4849667d-6fcc-4c1a-906c-a0e5e32f872d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>d326cd91-ff59-4f75-a870-a3cb5640b216</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>PageContent_txtBGValidDate</value>
      <webElementGuid>c0912677-e0b1-4cf6-93f0-ecc4aee21dd5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>c3478485-7584-4221-bc73-805ef74e3ec7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>bb081f12-9ca0-4891-86ad-e30170e6907d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>MM-DD-YYYY</value>
      <webElementGuid>a8a0dad7-c957-483b-aba2-13d203b3fda4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;PageContent_txtBGValidDate&quot;)</value>
      <webElementGuid>a2e5231e-a562-4020-b91e-24b3bf243614</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='PageContent_txtBGValidDate']</value>
      <webElementGuid>9a1df836-266a-4012-9051-3ab604469332</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='PageContent_BGDiv']/div[5]/div[2]/input</value>
      <webElementGuid>8c4affe6-ed20-4661-bb81-02fa19946784</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[5]/div[2]/input</value>
      <webElementGuid>d4bcdd7d-18b8-4f84-9690-31c96a2f9559</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'ctl00$PageContent$txtBGValidDate' and @type = 'text' and @id = 'PageContent_txtBGValidDate' and @placeholder = 'MM-DD-YYYY']</value>
      <webElementGuid>c52ae51a-6dce-4377-8f81-764e5ddd2c00</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
