<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Road  Street Name_txtRoadStreetNm</name>
   <tag></tag>
   <elementGuidId>09272d5f-8c30-456a-b0c6-3fd01a6ec91c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#txtRoadStreetNm</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtRoadStreetNm']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>09ab0527-e73f-4177-97da-05bd6deb4573</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>txtRoadStreetNm</value>
      <webElementGuid>32193a5d-7a14-4c98-9094-02cd020238de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>83a7d1af-dfba-430e-8185-34082062a51b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtRoadStreetNm</value>
      <webElementGuid>f5983d8d-d247-49a8-9fdf-4f0f9e8c48ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>1c3b447c-3ca3-4078-b6c6-ff5e5cb78bc4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtRoadStreetNm&quot;)</value>
      <webElementGuid>a278b44a-6763-4eca-8703-ec0334b17fca</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtRoadStreetNm']</value>
      <webElementGuid>1b0d9452-5091-496f-a573-702f22b651bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='accordion']/div[2]/div/div[4]/div/h5/input</value>
      <webElementGuid>d379d844-ef27-4683-b451-3f1975ae65f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/h5/input</value>
      <webElementGuid>b462d6c7-c75b-43f1-a14b-833fbd14b71d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'txtRoadStreetNm' and @type = 'text' and @id = 'txtRoadStreetNm']</value>
      <webElementGuid>c5b6a9ca-4175-48c7-ae24-cea043c292e3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
