<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__txtPlotNo</name>
   <tag></tag>
   <elementGuidId>8615d182-0799-47b7-ba28-ba502f4d6c99</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#txtPlotNo</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtPlotNo']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a3e166c7-89bf-4ca5-ad73-35d716ad5fbd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>txtPlotNo</value>
      <webElementGuid>30227b24-6bba-4a8c-b22b-7f9e6579a317</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>1220de86-3530-4c7b-a8fa-64f99c51245c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtPlotNo</value>
      <webElementGuid>e987f465-697a-4217-b9b0-61fc4fe1aa31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>84ed3612-8ad8-4842-ae80-5b2d628fa4a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtPlotNo&quot;)</value>
      <webElementGuid>75e84195-b12f-4708-b5f6-a177a4b6fc54</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtPlotNo']</value>
      <webElementGuid>6953574f-d43c-4aa0-8394-780bac810f40</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='divPlotNo']/input</value>
      <webElementGuid>bec96f76-6dcc-45f2-aca5-ca3d48f6fe7c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div/input</value>
      <webElementGuid>f1308147-c282-489b-9b03-69f48113e26c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'txtPlotNo' and @type = 'text' and @id = 'txtPlotNo']</value>
      <webElementGuid>5cf8f28a-cbad-4add-9784-bf300ae51dd3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
