<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_This plot belongs to_rdbIsThisPlotHaving</name>
   <tag></tag>
   <elementGuidId>77dad95e-add1-4a8a-92a5-40e1793a9027</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#rdbCTSNo</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='rdbCTSNo']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>447973d1-a969-4dfc-8ddc-7729e3f27c27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>rdbCTSNo</value>
      <webElementGuid>9b5de4b3-5e88-4b76-b76f-f2bf7efc5a95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>7442ae0c-0a3e-4f75-94c7-d41d8d0f2d64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>rdbIsThisPlotHaving</value>
      <webElementGuid>6eb1f496-2ecb-4ee4-8a83-8987ecb59b1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>rdbCTSNo</value>
      <webElementGuid>9e331d8b-a2c2-4446-a16e-f5d9efd7b364</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>clkIsThisPlotHavingCTS(1);</value>
      <webElementGuid>ba762591-def8-41a0-bbca-70e8c49a8b96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rdbCTSNo&quot;)</value>
      <webElementGuid>16ba9920-2623-4ba8-b37a-9bed179788bb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='rdbCTSNo']</value>
      <webElementGuid>b91935ef-089e-47a8-b918-bd26e3d680aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Div4']/div[2]/div[5]/div/input</value>
      <webElementGuid>560ce7a3-231d-4b75-81a0-1cf16c389f58</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/input</value>
      <webElementGuid>cb446c5d-2bc6-498c-9cec-bddccb1cce53</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'rdbCTSNo' and @type = 'radio' and @name = 'rdbIsThisPlotHaving']</value>
      <webElementGuid>7a5adb17-9c6c-4553-979a-0e55875980eb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
