<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Lattitude_txtLattitude</name>
   <tag></tag>
   <elementGuidId>6c2f886f-4887-4ade-8360-b41b5204d628</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#txtLattitude</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtLattitude']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>42f046bf-9aec-4783-9b26-56cf6f2869ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>txtLattitude</value>
      <webElementGuid>4d3f1743-1586-4f85-b2aa-7c02b3485b8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>d9c37d11-d412-4d46-83f0-3a8d7205b8b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtLattitude</value>
      <webElementGuid>2ac44880-2419-43d1-9cb2-92d0d4047289</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>fb7d8a64-973e-42da-a1a8-2cd7b4083c67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtLattitude&quot;)</value>
      <webElementGuid>6328cac0-0d85-4b83-836a-cb04d9a800a1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtLattitude']</value>
      <webElementGuid>c4f5e781-ac43-4dc9-afa1-a8579543f1ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='accordion']/div[2]/div/div[6]/div/input</value>
      <webElementGuid>c909d7e4-1534-474d-a300-9df52689187f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[6]/div/input</value>
      <webElementGuid>e03f00f6-260f-4f76-91e9-22f8d010722b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'txtLattitude' and @type = 'text' and @id = 'txtLattitude']</value>
      <webElementGuid>d8c9e78d-2735-4773-86e8-f354ae323094</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
