<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__txtAddressofApplicant</name>
   <tag></tag>
   <elementGuidId>63dc9b82-2c40-4749-a815-e7dd2001d8e9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#txtAddressofApplicant</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtAddressofApplicant']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>252dc1cb-8e0b-4735-bff4-04568aa3309c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>txtAddressofApplicant</value>
      <webElementGuid>f8c11164-3b82-4c19-a6f7-35a3dddb324f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>83eaff5a-1405-42bd-956e-54cedfca7f04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtAddressofApplicant</value>
      <webElementGuid>654e3d19-25cb-40fa-bc73-ca1dbf6032ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>af1e0c08-2ddf-48eb-ac1f-1e63d273ec69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtAddressofApplicant&quot;)</value>
      <webElementGuid>fa966274-7787-4fc0-8cda-602c28de7b1c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtAddressofApplicant']</value>
      <webElementGuid>76e7dd80-a168-4d66-9059-c775f36d7f35</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='accordionCAF']/div[8]/div/div[2]/input</value>
      <webElementGuid>384a2e25-14e1-4d63-818c-cf18e25c8b43</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div/div[2]/input</value>
      <webElementGuid>e78eabef-ec69-4de4-8245-918a5b9b80a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'txtAddressofApplicant' and @type = 'text' and @id = 'txtAddressofApplicant']</value>
      <webElementGuid>f56a762d-04f4-42dd-9bcb-b147431550fe</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
