<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Name_Addbuildingtxt_BuildingName</name>
   <tag></tag>
   <elementGuidId>9754ca73-b113-4a62-87ae-09042983089f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Addbuilding_txt_BuildingName</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Addbuilding_txt_BuildingName']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>795e0efe-91c9-4789-917f-6e90462200f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Addbuilding$txt_BuildingName</value>
      <webElementGuid>c309fb18-2390-44d6-bf98-a101fda7f9f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Addbuilding_txt_BuildingName</value>
      <webElementGuid>8d623156-643f-4545-a603-20e2e3f2ce2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>32e8295b-cc54-45a5-968f-348ec47d5ba3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter name</value>
      <webElementGuid>f987a024-e483-45f0-a315-c98292c386ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>de462f78-108e-45de-86c4-82c8b98ee15d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Addbuilding_txt_BuildingName&quot;)</value>
      <webElementGuid>cb0db173-61d4-47e2-a02a-eada65295cf6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Addbuilding_txt_BuildingName']</value>
      <webElementGuid>5f5bfdb2-6f70-4727-895e-d6156c1c8887</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Addbuilding_div_AddBuilding']/div/div/div/div/input</value>
      <webElementGuid>816d41fd-6c3b-41f2-99e1-5d68fe903a44</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[2]/div/div/div/div/div/input</value>
      <webElementGuid>762a5b26-c5f9-46ca-968c-2523b6f9a892</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'Addbuilding$txt_BuildingName' and @id = 'Addbuilding_txt_BuildingName' and @placeholder = 'Enter name' and @type = 'text']</value>
      <webElementGuid>1850e241-4f7e-4a9b-a632-8dcfa52d70ef</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
