<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Gross Construction Area (Sq. mtrs.)_A_7285a7</name>
   <tag></tag>
   <elementGuidId>38c956bd-541a-42db-9613-99d5183cb2dc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Addbuilding_btn_save_1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Addbuilding_btn_save_1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>74943bf2-4620-438c-bc71-48b248ca6910</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>8940cd53-66e6-4b3a-b50f-4a3fdefa661a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Addbuilding$btn_save_1</value>
      <webElementGuid>a67d74f4-aad4-4844-8f3f-5fafebd208d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>  Save  </value>
      <webElementGuid>c46e6101-f6bc-4483-86ef-558a670df3d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>return Validate();WebForm_DoPostBackWithOptions(new WebForm_PostBackOptions(&quot;Addbuilding$btn_save_1&quot;, &quot;&quot;, true, &quot;&quot;, &quot;&quot;, false, false))</value>
      <webElementGuid>eb803a9a-6b42-4297-bb0b-2728c8c551c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Addbuilding_btn_save_1</value>
      <webElementGuid>2b988677-32c6-49cf-bfc9-d077ebb4df89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary save-new-details mr15</value>
      <webElementGuid>a1a2ba9a-b25f-4db8-9bdb-c2e209a7adb9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Addbuilding_btn_save_1&quot;)</value>
      <webElementGuid>988aeadb-4558-4c05-82a9-6edf21c7ef90</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Addbuilding_btn_save_1']</value>
      <webElementGuid>0e3f4d04-6de0-43f5-94d1-eaa4770e8945</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Addbuilding_div_AddBuilding']/div/div[5]/div/input</value>
      <webElementGuid>627dcc50-0ae2-4791-9a66-ba2347e7f726</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/input</value>
      <webElementGuid>9632bff8-7ecb-4b88-a298-a14445b056dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit' and @name = 'Addbuilding$btn_save_1' and @id = 'Addbuilding_btn_save_1']</value>
      <webElementGuid>92fcf55b-dc31-4795-a7be-64bc38d862df</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
