<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Planning Authority for the project_rd_c3a9de</name>
   <tag></tag>
   <elementGuidId>0219be71-806d-4e7e-b0e9-90f5882d8ef4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#rdbPlotInfo1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='rdbPlotInfo1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e1131c13-dd94-4130-a292-eb38e942e349</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>rdbPlotInfo1</value>
      <webElementGuid>2fa0ba9d-9a12-4a92-8c4b-56d218141328</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>1bb37688-1664-42ac-937a-97c124ef8309</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>rdbPlotInfo</value>
      <webElementGuid>c8b75451-71ca-4a9e-b2f2-80f0e19a002f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>b17bbc01-5df2-45e6-b1b0-2e01a707723f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rdbPlotInfo1&quot;)</value>
      <webElementGuid>3985cb5d-45b4-4053-b2e1-17dcf64932fa</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='rdbPlotInfo1']</value>
      <webElementGuid>57bd0532-ce88-4436-a199-e9b0ccf80a63</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Div4']/div[2]/div/div/div/div/h5/span[3]/input</value>
      <webElementGuid>ce3bc9b9-2072-4ca6-8177-6878ca6f5bce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[3]/input</value>
      <webElementGuid>9cea2d20-2bd2-44d3-bd97-55a3ac7e9299</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'rdbPlotInfo1' and @type = 'radio' and @name = 'rdbPlotInfo']</value>
      <webElementGuid>f40609b1-36e2-471e-8921-2589aaaf795f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
