<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Yes_rdoRoadPresent</name>
   <tag></tag>
   <elementGuidId>5c3ca81e-3493-42c8-8299-01b127d3d955</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#rdbInternalLayoutpresent1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='rdbInternalLayoutpresent1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8e20dbef-4a00-42bd-b05c-ab0f6d7d2eff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>rdbInternalLayoutpresent1</value>
      <webElementGuid>4f9f2a8c-35d1-465b-969d-49174eda4c52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>4b7e09ac-e098-49db-aeb5-66c3add1b84f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>rdoRoadPresent</value>
      <webElementGuid>63147c25-908c-47bc-a74a-cb9620968ea4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>rdbInternalLayoutpresent1</value>
      <webElementGuid>7dfb3784-acf0-40ab-a33a-8d07971b048c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>clkInternalLayoutpresent(1);</value>
      <webElementGuid>eb793f40-e663-4811-b6fe-5dd5da61b211</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rdbInternalLayoutpresent1&quot;)</value>
      <webElementGuid>cb5b0cd3-1707-4e0c-8a77-dec3f1a4d66e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='rdbInternalLayoutpresent1']</value>
      <webElementGuid>58ced468-7474-485f-b766-219ca825d166</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='divInternalRoad']/div/div/input[2]</value>
      <webElementGuid>9746835b-f6fd-4da1-9a27-ba8a5a75b1f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/div/div/input[2]</value>
      <webElementGuid>bb242584-9352-4526-a885-39a8e15a670f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'rdbInternalLayoutpresent1' and @type = 'radio' and @name = 'rdoRoadPresent']</value>
      <webElementGuid>1273a201-82c6-4b65-aa5f-46b63bd7f9fe</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
