<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Project Info_btnsaveCAF</name>
   <tag></tag>
   <elementGuidId>08b65c42-6cf3-4bf7-9644-a54f248e278d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#btnsaveCAF</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='btnsaveCAF']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ca81287e-1a1d-40ad-b83b-c6dd6844faf1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>btnsaveCAF</value>
      <webElementGuid>5aded2a2-7ab2-4cb7-bb69-d543e419327c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>1a6026ea-cc10-462b-b04d-fd2f2e436bc6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btnsaveCAF</value>
      <webElementGuid>9e3353ff-7734-46b7-a42f-10f504addc86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>javascript:clkSaveCAF()</value>
      <webElementGuid>9515018c-bceb-4e3a-ae4c-69321a65fdc2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary save-details</value>
      <webElementGuid>a1c77edd-7038-4ff9-80b0-81de6648c45b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Save</value>
      <webElementGuid>22fb855a-fee5-486a-8143-7aeed6020724</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btnsaveCAF&quot;)</value>
      <webElementGuid>94bee104-d9a4-4aeb-a4da-b29346bdaac8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='btnsaveCAF']</value>
      <webElementGuid>bc94d882-db39-49c0-bd8e-ee295b4464be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='accordionCAF']/div/input</value>
      <webElementGuid>b0c51baf-a78f-42b5-887a-505b4bbd1ad3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/input</value>
      <webElementGuid>ff75b053-cafb-4b73-8352-3f2a5d1777c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'btnsaveCAF' and @type = 'button' and @id = 'btnsaveCAF']</value>
      <webElementGuid>fdf7980e-378d-478e-b2e3-28ac0e56f00d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
