<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_DP Zone_txtPlotDPZone</name>
   <tag></tag>
   <elementGuidId>42e77220-54dd-4a5b-8f83-edd5b316be60</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#txtPlotDPZone</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtPlotDPZone']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2bc05b7e-1ba9-4296-8d82-ce46a6bd80cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>txtPlotDPZone</value>
      <webElementGuid>6c527630-9570-43ff-ae92-9abefb839d3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>9a22faf0-f414-419f-bd91-36d22d73a4c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtPlotDPZone</value>
      <webElementGuid>9c1d4e12-781f-480c-a5bb-5c17ad489800</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>892458f0-b808-4048-8951-f4b8ca45481c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtPlotDPZone&quot;)</value>
      <webElementGuid>1a5ab43f-503a-4a2c-9791-8bad57f1260e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtPlotDPZone']</value>
      <webElementGuid>0b9c61b6-a1e2-43d1-8452-4906a0cc8889</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='accordion']/div[2]/div/div[4]/div[2]/input</value>
      <webElementGuid>fea19ace-d7d0-4d6c-9a17-698b57acf1ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[4]/div[2]/input</value>
      <webElementGuid>ac3e7dc5-ecf3-4129-92c0-7056c544f36f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'txtPlotDPZone' and @type = 'text' and @id = 'txtPlotDPZone']</value>
      <webElementGuid>31773c5b-b760-46ea-92f8-2275c05933af</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
