<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__txtLandmark</name>
   <tag></tag>
   <elementGuidId>22efeb4e-f096-4fc0-a22b-172ca0208042</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#txtLandmark</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtLandmark']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a92ae8ae-271e-4bf3-99bc-8cdef688daa6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>txtLandmark</value>
      <webElementGuid>a02e5514-5af8-4176-b708-5cb16eb506d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>8823e5b1-e574-42e7-86f8-6fd9a1f99f19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtLandmark</value>
      <webElementGuid>96928c3d-009f-4a83-a372-f2399a770ae1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>dddd1e45-e92c-4768-83d9-deb1bf0e7386</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtLandmark&quot;)</value>
      <webElementGuid>af10cf58-6e68-4344-bfee-a35902b96e00</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtLandmark']</value>
      <webElementGuid>7d4ff3e1-7ed6-49e2-a39e-12e50ed81513</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='accordionCAF']/div[5]/div/div[2]/input</value>
      <webElementGuid>2f967963-a286-488b-bee0-1922a7b2421a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div[2]/input</value>
      <webElementGuid>d8d95f0d-9ae5-4dc6-8d8d-043ecd3d1a86</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'txtLandmark' and @type = 'text' and @id = 'txtLandmark']</value>
      <webElementGuid>e9190f27-dfd4-4a53-9021-c5883cd0bc24</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
