<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Height  (Mtr.)_AddbuildingtxtHeight</name>
   <tag></tag>
   <elementGuidId>c5ce1732-9dc4-4346-81ea-e4afb0596307</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Addbuilding_txtHeight</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Addbuilding_txtHeight']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0b229a7b-b5eb-463c-bc5f-185720596cc4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Addbuilding$txtHeight</value>
      <webElementGuid>43ef6430-7922-43f8-9d62-d1a8bc48eaeb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Addbuilding_txtHeight</value>
      <webElementGuid>fb8298d1-0253-445e-9787-09dee464d7e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>397430b1-7de5-40aa-91f1-1676bf83840c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>d1912eb3-b243-4d42-9c64-45eafd8c3abd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter</value>
      <webElementGuid>bd347668-e8a8-452e-8093-f97e5612b6db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Addbuilding_txtHeight&quot;)</value>
      <webElementGuid>f2e5aa61-77bc-415b-b3a5-72cb7929a20d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Addbuilding_txtHeight']</value>
      <webElementGuid>94821abb-26b5-4575-8c80-7750f9afd151</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Addbuilding_div_AddBuilding']/div/div[3]/div/div[2]/input</value>
      <webElementGuid>55185f4e-8895-4a13-9181-51d7ecfc83b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div[2]/input</value>
      <webElementGuid>536a4e02-9e78-4ed6-b1d7-c656b70b8e66</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'Addbuilding$txtHeight' and @id = 'Addbuilding_txtHeight' and @type = 'text' and @placeholder = 'Enter']</value>
      <webElementGuid>0ad1bd67-bf2e-4518-956e-0215ef81c2ed</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
