<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Least Area_ucAreaRptAreaDetailsctl01b_d89a03</name>
   <tag></tag>
   <elementGuidId>3241f4cc-999d-4d08-85e3-4e7f054e6257</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ucArea_RptAreaDetails_btnInsRow_0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ucArea_RptAreaDetails_btnInsRow_0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e4c8c5ff-aefe-40a9-9cfa-7ff085ec6258</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>636ff1c0-7df2-4a2c-85c0-a1bb5cb2dee7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ucArea$RptAreaDetails$ctl01$btnInsRow</value>
      <webElementGuid>54b98152-692a-4360-88b2-f40465b74b2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Extract</value>
      <webElementGuid>a6d86291-3473-4282-9c1d-f7b1e8c6702b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>javascript:WebForm_DoPostBackWithOptions(new WebForm_PostBackOptions(&quot;ucArea$RptAreaDetails$ctl01$btnInsRow&quot;, &quot;&quot;, true, &quot;&quot;, &quot;&quot;, false, false))</value>
      <webElementGuid>630fde65-428e-4cd4-be75-4bc091f7ca4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ucArea_RptAreaDetails_btnInsRow_0</value>
      <webElementGuid>b6e2dc72-6ac9-405d-a03e-07ab71323964</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-tertiary blue-plus</value>
      <webElementGuid>dc6ca26c-092f-46ae-96a6-99e592ceafb9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ucArea_RptAreaDetails_btnInsRow_0&quot;)</value>
      <webElementGuid>ee741355-8a55-4629-b3e7-626009498df1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ucArea_RptAreaDetails_btnInsRow_0']</value>
      <webElementGuid>e7f9db65-4bb3-4a1b-838e-4c3a23ce2539</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='collapse1']/div/div/div/div[2]/div/table/tbody/tr/td/div/input</value>
      <webElementGuid>e89f0914-2f3a-4a03-aa2d-c7bf151cc3bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/div/input</value>
      <webElementGuid>63652ce3-dacc-4a47-b591-035a6a1e3ffd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit' and @name = 'ucArea$RptAreaDetails$ctl01$btnInsRow' and @id = 'ucArea_RptAreaDetails_btnInsRow_0']</value>
      <webElementGuid>6d1505d5-23a3-4a37-89e6-1e482cc26c5c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
