<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_CTS No_rdbIsThisPlotHaving</name>
   <tag></tag>
   <elementGuidId>6e17f051-669f-4f5a-82ef-4e36b502cb07</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#rdbCSNo</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='rdbCSNo']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>611eb57e-9076-43bc-9bad-1156606d738a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>rdbCSNo</value>
      <webElementGuid>63ac0aae-c078-4f86-a253-3b7d3686e670</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>e965f9dc-2d92-4396-a29a-876f1817458d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>rdbIsThisPlotHaving</value>
      <webElementGuid>766180cb-d459-4e87-9adf-9a58cacd3c81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>rdbCSNo</value>
      <webElementGuid>fd85c7b3-1519-4885-b516-ed135259865f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>clkIsThisPlotHavingCTS(0);</value>
      <webElementGuid>21e2f9b8-cff2-4fc3-bd74-b42f6de8a056</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rdbCSNo&quot;)</value>
      <webElementGuid>861fb6d3-c1eb-4605-9b16-694489ecc9bb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='rdbCSNo']</value>
      <webElementGuid>d771a922-6be9-439c-8eff-ba96539fb77b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Div4']/div[2]/div[5]/div/input[2]</value>
      <webElementGuid>0d574557-ffd4-4dae-926a-7e6ef3d905e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/input[2]</value>
      <webElementGuid>2b215954-78b2-4d65-9b33-d160da3824af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'rdbCSNo' and @type = 'radio' and @name = 'rdbIsThisPlotHaving']</value>
      <webElementGuid>3b085498-bc81-4753-97a3-e9e6f7552cb9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
