<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Longitude_txtLongitude</name>
   <tag></tag>
   <elementGuidId>f38eff8c-e92e-4c21-bf75-12628914bc7c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#txtLongitude</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtLongitude']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>20a4d54b-d306-4610-b5a8-a40935b5550e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>txtLongitude</value>
      <webElementGuid>78182e80-1257-4b37-a282-c6dee4160919</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>6e297641-4d13-43b4-a76e-74850571d638</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtLongitude</value>
      <webElementGuid>4b6857f0-0e3b-49a7-9709-13f01eede451</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>cd4498e5-89af-4cc4-804b-3f94c7452e71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtLongitude&quot;)</value>
      <webElementGuid>917c009b-684d-4738-8148-8198ec6e3f18</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtLongitude']</value>
      <webElementGuid>aaf60d7e-aaf2-4ce9-9cf5-29663362f53c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='accordion']/div[2]/div/div[6]/div[2]/input</value>
      <webElementGuid>ddb14491-c126-4aa9-9fc3-83720e1bdee3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div[2]/input</value>
      <webElementGuid>6ab763c9-a873-4efa-9b49-d893f46b270d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'txtLongitude' and @type = 'text' and @id = 'txtLongitude']</value>
      <webElementGuid>8a08dbbf-4662-4c99-b395-4464ed5ac351</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
