<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Total_ucAreaRptAreaDetailsctl01btnSave</name>
   <tag></tag>
   <elementGuidId>948a06d1-ff7f-4e85-a506-b220b6349bb8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ucArea_RptAreaDetails_btnSave_0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ucArea_RptAreaDetails_btnSave_0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>601f43b2-c98e-4998-a8dc-e0af662f1ab3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>bd0743b2-6529-40c6-bf4e-0afb0810747e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ucArea$RptAreaDetails$ctl01$btnSave</value>
      <webElementGuid>8626bb15-c2a9-4192-b518-165a9abcd735</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Save</value>
      <webElementGuid>856e24ba-8148-476b-abe1-5a12a61a0d52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>javascript:WebForm_DoPostBackWithOptions(new WebForm_PostBackOptions(&quot;ucArea$RptAreaDetails$ctl01$btnSave&quot;, &quot;&quot;, true, &quot;&quot;, &quot;&quot;, false, false))</value>
      <webElementGuid>5ac49209-feb7-49eb-88d8-d3c8ffc6e35d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ucArea_RptAreaDetails_btnSave_0</value>
      <webElementGuid>eeda7ecd-c107-454b-9df0-8325013b80d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-tertiary save-details</value>
      <webElementGuid>40822d75-bd71-4fea-8518-f3b1738352dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ucArea_RptAreaDetails_btnSave_0&quot;)</value>
      <webElementGuid>57c73e44-e25c-47df-935d-0f1ac5446781</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ucArea_RptAreaDetails_btnSave_0']</value>
      <webElementGuid>0904ea5e-4434-47d2-8c28-14c32200d3aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='collapse1']/div/div/div/div[3]/div/input</value>
      <webElementGuid>22727bcd-2f31-4db0-8e92-4e9fb20f8091</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div[3]/div/input</value>
      <webElementGuid>56803458-399c-4ec5-8079-ec83ed7daa68</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit' and @name = 'ucArea$RptAreaDetails$ctl01$btnSave' and @id = 'ucArea_RptAreaDetails_btnSave_0']</value>
      <webElementGuid>d8383150-fd09-4d08-84bc-a34bf336ae4e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
