<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Licensed Surveyor</name>
   <tag></tag>
   <elementGuidId>b84e2aef-05ab-49cd-894d-de22341029f5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#head_spnDesignation</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='head_spnDesignation']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>1cb5216f-c109-4de0-ba4c-bf75f8ede000</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>head_spnDesignation</value>
      <webElementGuid>def97ad7-e8c9-4e18-a4ed-80e5304a5e0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>position</value>
      <webElementGuid>8cdb322b-11f8-4ab9-ad64-929b87f517d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Licensed Surveyor</value>
      <webElementGuid>7759f115-7ead-4ff1-ad19-267fbd236767</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;head_spnDesignation&quot;)</value>
      <webElementGuid>7450603d-57ed-404f-bf48-067c32966cbe</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='head_spnDesignation']</value>
      <webElementGuid>7070bee8-76c9-4450-a1a7-2d9f4506253f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//header[@id='head_applicantHeader']/div/div[3]/div/div[3]/div[2]/span[2]</value>
      <webElementGuid>7872457b-6106-4d49-8f27-1770a8add453</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SUNIL RAMCHANDRA DE...'])[1]/following::span[1]</value>
      <webElementGuid>a29264ce-92b5-4518-8b09-082742d037fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ADFO GS'])[1]/following::span[2]</value>
      <webElementGuid>718201ce-7fa6-40ff-900e-b57fa5831db2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Log Out'])[1]/preceding::span[1]</value>
      <webElementGuid>c29eed66-d460-4cf0-a441-9dd2991c2999</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Licensed Surveyor']/parent::*</value>
      <webElementGuid>1c3413ee-cd9c-4ae0-ab68-d38d46924d43</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/span[2]</value>
      <webElementGuid>0ff4b898-108c-44a9-89b5-c7ffc3eadafa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'head_spnDesignation' and (text() = 'Licensed Surveyor' or . = 'Licensed Surveyor')]</value>
      <webElementGuid>253ce550-a21b-403c-8c30-e754bf7ffa8c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
