<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Select</name>
   <tag></tag>
   <elementGuidId>0c06d295-0e60-42fd-aa1b-91d410892ad6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.chosen-single > span</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='cboConsultant_chosen']/a/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>4ced4842-0860-4a7b-a496-888f57754322</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select</value>
      <webElementGuid>5c1a3a6d-e60f-450c-bcf6-5ce7cf151d09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cboConsultant_chosen&quot;)/a[@class=&quot;chosen-single&quot;]/span[1]</value>
      <webElementGuid>f052d6c2-b51b-4267-8ae3-01dcfc72a780</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cboConsultant_chosen']/a/span</value>
      <webElementGuid>75697792-e61e-4059-85a1-167818b10bf7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Plumbing Consultant'])[1]/following::span[1]</value>
      <webElementGuid>59b896f1-81df-453c-818a-11f35960c5dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select'])[4]/preceding::span[1]</value>
      <webElementGuid>dec1eb6e-59d3-4388-ad51-e97e1275ee7f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Abdul Sattar Abdul Gani'])[2]/preceding::span[1]</value>
      <webElementGuid>06eb8820-3b34-4a31-9fdb-b3511314b76c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/a/span</value>
      <webElementGuid>a047b0e9-6c94-4c46-aae7-174b8955b990</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Select' or . = 'Select')]</value>
      <webElementGuid>86a59e80-f99a-42ea-b855-a5e8d5969981</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
