<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea__txtPropertyAddress</name>
   <tag></tag>
   <elementGuidId>d3f4373a-f444-4d4f-b6b3-3f47a95dadfe</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#txtPropertyAddress</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='txtPropertyAddress']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>b85c5e1d-e139-462a-a9c8-22e7fad476d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>txtPropertyAddress</value>
      <webElementGuid>bed46db2-ffde-430f-91f0-81589e06a5ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>fe41c4a9-e567-46bc-9586-e7abe4eb224a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cols</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>704ce7e2-e819-40c5-8967-87d982a6b61b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtPropertyAddress</value>
      <webElementGuid>ecb0a6a3-687e-470c-808b-beb82577d8e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>f082acac-b714-4156-9e95-3dfee7d28a50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtPropertyAddress&quot;)</value>
      <webElementGuid>846bb0e1-2ef8-48f0-a55f-6312bbf5ba1c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='txtPropertyAddress']</value>
      <webElementGuid>e1e1d06e-6c86-44d1-80c3-00cf5d029d62</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='accordionCAF']/div[5]/div/div/textarea</value>
      <webElementGuid>8de49bc4-06df-41b1-94a2-c71f47fea60d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/textarea</value>
      <webElementGuid>fc93bbcc-bba2-4e80-8010-d359f2d73c29</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = 'txtPropertyAddress' and @id = 'txtPropertyAddress']</value>
      <webElementGuid>48dfd73c-9c8d-436b-b219-b53298d0eb05</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
