<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea__txtResidentialAddress</name>
   <tag></tag>
   <elementGuidId>7a9f7d29-fb6d-4893-8b56-c5f5618e6d38</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#txtResidentialAddress</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='txtResidentialAddress']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>54e01232-c3ca-4487-8a26-afb6c7d477d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>txtResidentialAddress</value>
      <webElementGuid>4ee13080-5e5f-47d9-b59e-c3edb11f0aa8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>a73bdcbc-bf68-4b65-8e86-2aac92a6bcfc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cols</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>2966739e-bc10-40e7-b6a9-2c1b7bca1c1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtResidentialAddress</value>
      <webElementGuid>dd06aeab-25c4-4cab-881c-a38b8658de7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>7e08f17b-fa83-4673-802d-680b22382945</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtResidentialAddress&quot;)</value>
      <webElementGuid>547d9dab-d7eb-48f9-962a-b831748c355e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='txtResidentialAddress']</value>
      <webElementGuid>83598a08-3e58-465a-8c87-8519acc250b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='divAddDetails']/div[3]/div/div[2]/textarea</value>
      <webElementGuid>34bfef13-3bf1-4c6c-85f5-48ea81cf9ea5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/textarea</value>
      <webElementGuid>e2d6f72f-d847-4332-baca-a0bdc70543c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = 'txtResidentialAddress' and @id = 'txtResidentialAddress']</value>
      <webElementGuid>3c2ad88a-b3ca-4f27-b133-4bf81cbbfbf9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
