<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Proposed CTS No. for this project_arrCTS</name>
   <tag></tag>
   <elementGuidId>7be1ffb6-06cf-4f94-a387-f1b08ca01548</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#arrCTS</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='arrCTS']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>32ebd295-b4ca-430e-9d88-32c97d64ec3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>arrCTS</value>
      <webElementGuid>7db6d9e8-770a-45c6-b9fc-fbc13c197855</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>f711a897-0a3c-43eb-bff1-97d31185f905</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cols</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>a138a98d-0b78-44bc-b251-3c73675a5da7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>arrCTS</value>
      <webElementGuid>af778282-fe1a-48f8-bdc5-48d262f75ba6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>f5e35a65-b538-4d6a-911c-e07f14b8592b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>plcaeholder</name>
      <type>Main</type>
      <value>Multiple CTSNO/CSNO please seperreted by Comma(ex:121,134,154)</value>
      <webElementGuid>94fa9d74-6166-41c2-9fe1-9ed8ab09b49f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;arrCTS&quot;)</value>
      <webElementGuid>72410290-a9c6-41bb-be42-979f944cf601</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='arrCTS']</value>
      <webElementGuid>532491a2-3a78-4350-afdc-2a54dbfd8a5f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='divCTSNo']/div/div/textarea</value>
      <webElementGuid>f4b2b2d2-0606-4a36-a3bf-10e7e836bada</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/div/div/textarea</value>
      <webElementGuid>e0046d67-4e8c-4532-bdc2-341d527a5145</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = 'arrCTS' and @id = 'arrCTS']</value>
      <webElementGuid>9bcffb51-edb2-452e-bcbe-43d04d284d43</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
